version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    container_name: basic-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: basic-nginx
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:latest
    container_name: basic-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_TIME_ZONE: 'America/Sao_Paulo'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"

volumes:
  mysql_data: